### PR TITLE
Added generic institution choices

### PR DESCRIPTION
**Pull request by alaric-dfe**
- Added `GENERIC_INSTUTITIONS`
- Added `INSTITUTIONS_INCLUDING_GENERICS`, a combination of `GENERIC_INSTUTITIONS` and `INSTITUTIONS`

### CODE REVIEW

**Review by edwardhorsford — COMMENTED** [review]
Thanks for doing this @alaric-dfe! I might ask @frankieroberto to take a look at from a code point of view.

Would I be right in thinking this would be a breaking change?

**Comment by alaric-dfe** [comment]
I think adding extra records or fields to lists shouldn't _generally_ be considered breaking. Adding a generic option is perhaps a slightly different beast, however.

What I think the real question is: Should we merge it as-is, or instead leave `INSTITUTIONS` unchanged and add an `INSTITUTIONS_INCLUDING_GENERICS` as was done with `TYPES`? So code that wants the generics has to change to pick them up, but it's definitely not a breaking change for existing code.

**Comment by frankieroberto** [comment]
This feels backwards-incompatible with me - adding a generic institution within the `INSTITUTIONS` list is unexpected, and wouldn't be the behaviour we want on Apply (where we ask users to enter the name of the organisation if it’s not in our list).

Could we make this backwards-compatible by adding a `INSTITUTIONS_INCLUDING_GENERIC` option, and keeping `INSTITUTIONS` as just being the institutions?

**Comment by alaric-dfe** [comment]
Sure, I'll do that right after standups!

**Comment by frankieroberto** [comment]
@alaric-dfe great, thanks. Tag it as a 1.1.0 release?

**Review by frankieroberto — APPROVED** [review]

**Pull request merged**
