### PR TITLE
Add subject: English language and literature

### PR DESCRIPTION
**Pull request by frankieroberto**
This is a common combined degree subject which has been entered 199 times as a UK degree subject.

### CODE REVIEW

**Comment by frankieroberto** [comment]
Ideally we'd be able to list BOTH Hesa codes for the combined subject, but returning an array probably breaks a few things...

**Comment by edwardhorsford** [comment]
As this is a separate repo for reference data, I think this could include both HECOS codes now and Apply can decide to disregard them.

**Comment by edwardhorsford** [comment]
I still think this should output two HECOS codes before it gets merged.

**Comment by frankieroberto** [comment]
@edwardhorsford I've added a comment to this for now, and have opened issue #14 to suggest allowing multiple codes.

**Pull request merged**
