### PR TITLE
Add converter.rb and update Rakefile

### PR DESCRIPTION
**Pull request by ericaporter**
**Trello ticket:** [here](https://trello.com/c/usmgoJWN/2156-plt-6-dfereferencedata-add-script-to-allow-reference-data-to-be-converted-to-sqlite-db?filter=member:portererica) 

**Context:** 

Currently reference data gem is a static list of hashes, access to which is provided via Ruby or by generating static mappings in JSON format. Adding a script to the rakefile which converts the reference data to sqlite db will allow other non-RoRs (i.e. .net) applications to use it.

**This PR includes:**
1. A converter module which converts each table from dfe-reference-data to sqlite
2. A converter helper module which converts values / types to be compatible with sqlite
3. An update to the release.yml to make the versioned reference data db file accessible via Github
4. An update to the Rake file, adding a rake task to initiate the conversion of the tables listed in BIGQUERY_TABLES collection
5. Some tests to cover the new functionality N.B. comment out 
```
after(:each) do
    File.delete(versioned_output_file) if File.exist?(versioned_output_file)
end
``` 
to view the test sqlite files

**N.B. I have tested the sqlite file locally by running the rake task, inspecting the sqlite file checking all the tables existed, checking the scheme of the files and selecting data from the tables. I also tested that the file would be created as an artifact available on github by creating a test.yml which allowed me to view the file when I pushed a test branch. I was able to download the artifact file and interact with it**

### CODE REVIEW

**Review by asatwal — COMMENTED** [review]
Looks good @ericaporter - One question I had. I presume this is a straight forward dump of the data in the ruby hashes to the tables ? No building up of relationships between related entitiies if there are any ?

**Review by asatwal — COMMENTED** [review]
@ericaporter - Will running of the rake task be manual or do we deliver the SQLLite version with github actions ?

**Comment by ericaporter** [comment]
> @ericaporter - Will running of the rake task be manual or do we deliver the SQLLite version with github actions ?

@asatwal - I trigger the task in the release.yml which should make sure it is available without manually running the task but if necessary the task can be run alone

**Comment by ericaporter** [comment]
> Looks good @ericaporter - One question I had. I presume this is a straight forward dump of the data in the ruby hashes to the tables ? No building up of relationships between related entitiies if there are any ?

@asatwal - It's a flat structure atm in the gem. I could see the benefits of introducing relationships if we had the use cases to justify that. I can do a little delving to see if those exist / are likely to exist.

**Comment by asatwal** [comment]
> > Looks good @ericaporter - One question I had. I presume this is a straight forward dump of the data in the ruby hashes to the tables ? No building up of relationships between related entitiies if there are any ?
> 
> @asatwal - It's a flat structure atm in the gem. I could see the benefits of introducing relationships if we had the use cases to justify that. I can do a little delving to see if those exist / are likely to exist.

@ericaporter - I think to build those relationships between ref data entries we need use cases as you say. Those uses cases would lead to a better model I believe. So all good for now IMO. 👍

**Review by asatwal — APPROVED** [review]
👍 LGTM

**Review by carlosmartinez — APPROVED** [review]
looks eminently reasonable! nice work.

**Pull request merged**
